package it.scheduleplanner.dbutils;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Utility class for database operations.
 */
public class DBUtils {

    private static final String URL = "jdbc:sqlite:scheduleplanner.sqlite";

    /**
     * Initializes the database by creating the employee table if it does not exist.
     *
     * @throws SQLException if a database access error occurs
     */
    public static void initializeDatabase() throws SQLException {
        String createTableSQL = "CREATE TABLE IF NOT EXISTS employee ("
                + "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                + "name TEXT NOT NULL,"
                + "overTimeHours REAL,"
                + "weekendWorker BOOLEAN,"
                + "workingHours INTEGER)";

        try (Connection connection = getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(createTableSQL);
        }
    }

    /**
     * Establishes a connection to the database.
     *
     * @return the connection to the database
     * @throws SQLException if a database access error occurs
     */
    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL);
    }

    /**
     * Executes an update query.
     *
     * @param sql the query to execute
     * @throws SQLException if a database access error occurs
     */
    public static void executeUpdate(String sql) throws SQLException {
        try (Connection connection = getConnection();
             Statement statement = connection.createStatement()) {
            statement.executeUpdate(sql);
        }
    }

    /**
     * Executes a query that returns a result set.
     *
     * @param sql the query to execute
     * @return the result set generated by the query
     * @throws SQLException if a database access error occurs
     */
    public static ResultSet executeQuery(String sql) throws SQLException {
        Connection connection = getConnection();
        Statement statement = connection.createStatement();
        return statement.executeQuery(sql);
    }

    /**
     * Closes the connection to the database.
     *
     * @param connection the connection to close
     * @throws SQLException if a database access error occurs
     */
    public static void closeConnection(Connection connection) throws SQLException {
        if (connection != null) {
            connection.close();
        }
    }

    /**
     * Closes the statement.
     *
     * @param statement the statement to close
     * @throws SQLException if a database access error occurs
     */
    public static void closeStatement(Statement statement) throws SQLException {
        if (statement != null) {
            statement.close();
        }
    }

    /**
     * Closes the result set.
     *
     * @param resultSet the result set to close
     * @throws SQLException if a database access error occurs
     */
    public static void closeResultSet(ResultSet resultSet) throws SQLException {
        if (resultSet != null) {
            resultSet.close();
        }
    }
}